#!/usr/bin/env python3
"""Generic persistent vrnetlab launcher generated by dNLab."""
import json
from pathlib import Path
import vrnetlab

SPEC = json.loads(Path("/opt/generic/spec.json").read_text(encoding="utf-8"))

class GenericVM(vrnetlab.VM):
    def __init__(self):
        super().__init__(username="admin", password="admin", disk_image="/opt/generic/disk.qcow2",
                         ram=SPEC["ram_mb"], smp=str(SPEC["vcpu"]), min_dp_nics=SPEC["data_ports"])
        self.nic_type = "virtio-net-pci" if SPEC["nic_model"] == "virtio" else "e1000"
        self.num_nics = SPEC["data_ports"]
        self.conn_mode = "tc"
        if SPEC["firmware"] == "uefi":
            self.qemu_args.extend(["-drive", "if=pflash,format=raw,readonly=on,file=/opt/generic/OVMF_CODE.fd",
                                   "-drive", "if=pflash,format=raw,file=/persist/OVMF_VARS.fd"])

    def bootstrap_spin(self):
        if self.tn is not None:
            self.tn.close()
            self.tn = None
        self.running = True

class GenericVR(vrnetlab.VR):
    def __init__(self):
        super().__init__("admin", "admin")
        self.vms = [GenericVM()]

if __name__ == "__main__":
    vrnetlab.boot_delay()
    GenericVR().start()
